language: cpp

sudo: required

os:
  - linux
  - windows

branches:
    only:
      - master

stages:
  - "Building"
  - name: "Deployment"
    if: branch = master

env:
  - BUILD_TYPE=release
              
before_install:
  - source .travis/$TRAVIS_OS_NAME/before_install.sh

install:
  - source .travis/$TRAVIS_OS_NAME/install.sh

before_script:
  - source version.sh

script:
  - source .travis/$TRAVIS_OS_NAME/building.sh
  - source .travis/$TRAVIS_OS_NAME/testing.sh
  - source .travis/$TRAVIS_OS_NAME/viewer.sh

jobs:
    include:
      - stage: "Building"
      
        name: "Windows build with MingW-W64"
        os: windows
        compiler: gcc
        
      - name: "Linux build with GCC"
        os: linux
        dist: xenial
        services: xvfb
        compiler: gcc     
        
      - stage: "Deployment"
        
        name: "Coverage statistic collect"
        os: linux
        dist: xenial
        compiler: gcc
        services: xvfb 
        env: "BUILD_TYPE=coverage"
        script:
          - source .travis/$TRAVIS_OS_NAME/building.sh
          - source .travis/$TRAVIS_OS_NAME/testing.sh
          - source .travis/$TRAVIS_OS_NAME/coverage.sh